version: "3.9"

services:
  db:
    image: postgres:15
    container_name: helpdesk_db
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: helpdesk_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/helpdesk
      APP_NAME: API Helpdesk Intelligent
      APP_VERSION: 1.0.0
    ports:
      - "8001:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: helpdesk_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: